[script]
name = "HoYoPlay"
description = "Downloads the official HoYoPlay launcher installer and runs it in a prefix of your choice"
author = "reakjra"
icon = "./icon.png"

[[input]]
id = "prefix"
kind = "prefix"
picker = "path"
label = "Wine prefix"

[[step]]
task = "init_prefix"

[[step]]
task = "download"
url = "https://download-porter.hoyoverse.com/download-porter/2026/03/30/VYTpXlbWo8_1.14.2.345_1_0_hyp_hoyoverse_prod_202603021207_dJyiMLNi.exe"
dest = "${cache}/HoYoPlay-Setup.exe"

[[step]]
task = "run_exe"
exe = "${cache}/HoYoPlay-Setup.exe"

[game]
name = "HoYoPlay"
exe = "${prefix}/drive_c/Program Files/HoYoPlay/launcher.exe"

[game.env]
PROTON_NO_WM_DECORATION = "1"
